resources:
- name: repo
  type: git
  source:
    uri: https://github.com/litemars/CICD_concourse.git

jobs:
- name: task1
  plan:
  - get: repo
    trigger: true
  - task: test
    file: repo/task/task.yml
