resources:
- name: repo
  type: git
  source:
    uri: https://github.com/litemars/CICD_concourse.git

jobs:
- name: count
  plan:
  - get: repo
    trigger: true
  - task: count
    file: repo/task/task.yml
