/*
 * This file was automatically generated by EvoSuite
 */

package org.magee.math;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.magee.math.Rational;


/*
 * The following test cases have been automatically generated using EvoSuite. 
 * These unit tests contain assertions that reflect the current behavior of the  
 * class under test (Rational.java). However, since the class under test is faulty 
 * (i.e., there are bugs), the generated assertions may be wrong reflecting the 
 * incorrect behavior. Therefore, the assertions need to be analyzed and fixed. 
 *
 * Notes on Testing: There are bugs in Rational.java. A test revealing a bug should 
 * fail. Tests not revealing bugs should pass. You may fix obvious bugs, but do not 
 * waste time debugging.
 */

public class TestRationalExtended {

	@Test
	public void test0() throws Throwable {
		
		for (long i = 1; i < 5; i++) {
			Rational rational0 = new Rational((-1*i), (-1*i));
			Rational rational1 = rational0.abs();
			assertEquals(-1, rational1.intValue());
			assertEquals((-1*i), rational1.denominator);
		}
	}
}
